services:
  app:
    image: 68publishers/php:8.1-unit-dev-1.1.0
    container_name: web
    ports:
      - "80:8080"
      - "8080:8080"
    volumes:
      - .:/var/www/html:cached
    networks:
      - backend

networks:
  backend:
